[package]
authors = ["Charles R Earp <charles.r.earp@gmail.com>"]
categories = ["science"]
description = "A machine learning library for Rust."
edition = "2018"
homepage = "https://github.com/charles-r-earp/autograph"
keywords = ["neural-networks", "machine-learning", "deep-learning", "autograd", "gpu"]
license = "MIT/Apache-2.0"
name = "autograph"
readme = "README.md"
repository = "https://github.com/charles-r-earp/autograph"
version = "0.1.1"

[build-dependencies]
anyhow = "1.0.52"
bincode = "1.3.3"
bytemuck = "1.7.2"
hibitset = { version = "0.6.3", default-features = false }
once_cell = "1.8.0"
parking_lot = "0.11.1"
rspirv = "0.7.0"
walkdir = "2.3.2"
naga = { version = "0.8.1", features = ["spv-in", "validate", "msl-out", "hlsl-out"] }
fxhash = "0.2.1"

[build-dependencies.serde]
features = ["derive"]
version = "1.0.126"

[dependencies]
anyhow = "1.0.37"
bincode = "1.3.3"
crossbeam-channel = "0.5.1"
crossbeam-utils = "0.8.5"
derive_more = "0.99.11"
gfx-hal = "0.9.0"
hibitset = { version = "0.6.3", default-features = false }
num-traits = "0.2.14"
once_cell = "1.8.0"
parking_lot = "0.11.1"
rspirv = "0.7.0"
smol = "1.2.5"
thiserror = "1.0.23"
tinyvec = "1.2.0"
approx = "0.5.0"
prettytable-rs = "0.8.0"
spirv_cross = { version = "0.23.1", features = ["msl", "hlsl"] }
naga = { version = "0.8.1", features = ["spv-in", "validate", "msl-out", "hlsl-out"] }
fxhash = "0.2.1"

[dependencies.async-trait]
optional = true
version = "0.1.51"

[dependencies.autograph_derive]
optional = true
version = "0.1.0"
path = "autograph_derive"

[dependencies.bytemuck]
features = ["derive"]
version = "1.4.1"

[dependencies.byteorder]
optional = true
version = "1.4.3"

[dependencies.dirs]
optional = true
version = "3.0.2"

[dependencies.downloader]
optional = true
version = "0.2.6"

[dependencies.flate2]
optional = true
version = "1.0.20"

[dependencies.half]
features = ["num-traits", "bytemuck", "serde"]
version = "1.8.2"

[dependencies.http]
optional = true
version = "0.2.4"

[dependencies.ndarray]
default-features = false
features = ["serde"]
optional = true
version = "0.15.3"

[dependencies.rand]
optional = true
version = "0.8.4"

[dependencies.serde]
features = ["derive", "rc"]
version = "1.0.126"

[dev-dependencies]
approx = "0.4.0"
rusty-hook = "0.11.2"

[dev-dependencies.ndarray]
features = ["approx"]
version = "0.15.3"

[dev-dependencies.tokio]
features = ["full"]
version = "1.14.0"

[features]
bench = []
profile = []
derive = ["autograph_derive"]
device_tests = []
full = ["iris", "mnist", "kmeans", "neural_network"]
iris = ["ndarray"]
kmeans = ["learn", "rand"]
mnist = ["ndarray", "dirs", "flate2", "byteorder", "downloader", "http"]
neural_network = ["learn", "rand", "async-trait", "derive"]
learn = ["tensor"]
tensor = ["ndarray"]

[target]
[target."cfg(all(unix, not(target_os = \"ios\"), not(target_os = \"macos\")))"]
[target."cfg(all(unix, not(target_os = \"ios\"), not(target_os = \"macos\")))".dependencies]
gfx-backend-vulkan = "0.9.0"

[target."cfg(any(target_os = \"ios\", target_os = \"macos\"))"]
[target."cfg(any(target_os = \"ios\", target_os = \"macos\"))".dependencies]
gfx-backend-metal = "0.9.0"

[target."cfg(any(target_os = \"ios\", target_os = \"macos\"))".dependencies.gfx-backend-vulkan]
optional = true
version = "0.9.0"

[target."cfg(windows)"]
[target."cfg(windows)".dependencies]
gfx-backend-dx12 = "0.9.0"
gfx-backend-vulkan = "0.9.0"
